language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - mary.tarapuez7@gmail.com
script:
  #Test unitario y de integracion con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sonar-m4r1 -Dsonar.login=$SONAR
  #Deploy https://apaw-ep-themes.herokuapp.com
  deploy:
    provider: heroku
    api_key:
      secure: $HEROKU
    on:
      branch: master